language: java
install:
- bash install.sh
script:
- bash test.sh
before_script:
- bash pull.sh
after_success:
- bash push.sh
env:
  global:
    secure: jNnFk3WeLWZ6pcVWXqVPCqvq82Rq8ysk2B8rrjtwLdGGUg2UZjNCiUkeT+00qCEVwiHufc38apCT4nJ0i7GOPrhdEUf1FA+wDDiXelYwuxVQFgO5mznQEkvklPSd2qoeuwYL4u/3LSMEcQT7VCPFtwkaaTgI3jMxHR36Pq4+Uzb7hydVDvlL1QTPpElGD9Mnt8K197yX0R0tm7xcNby40fsjgaFoJ6dy19CmS5aN6PhLtoTNwwzk4SZj+rGtpWmzvf5VD+4hnQcFI0JDeERvRMY8e97j5NXObdD5RsbqNL/Rwf8SptzpmmwIwfL0CMpT8QAVCEFe5fduG2lg2AmLYlvsn79CHs68DcRkYzrIRbs9TZGzKGzHvMdSGQZVOtOBNRrOcsHHmUTwdeCD5CNWRPy7Ob7dvC5eCJ7QVN790rkvUwHGO3OjsGeraofSd3ZYKdcpKUOpRZ1u2kcAuSM25RZaXXOPt47+Zr/9LlIKIyr13rSmc8A8sIRRFD4Nde5XK4B7VwuZ7dXRM3G5gFIGYJgSLZUb0RlbZT7oil/MjN7KTRwgmg0DIx8ooD0gvc9VMBEthNMCXw5KyIz4vVGuD0usbYqPUIW/TRM4kdz5dUwkD659i6A2/3ouHdfA1kogVGnK5dZFXZeW1AJrke06IgSe9FT49CbkrPb1ImRaLg8=
